export const defaultProducts = [
  {
    id: "14",
    slug: "14-mukhi-rudraksha",
    name: "Original 14 Mukhi Rudraksha (Nepali) — Lab Certified Chaudah Mukhi Deva Mani",
    price: 36950,
    comparePrice: 59000,
    mrp: 59000,
    rating: 5.0,
    reviews: 142,
    reviewCount: 142,
    img: "/images/product-1mukhi.jpg",
    images: [
      "/images/product-1mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-7mukhi.jpg",
      "/images/product-mala.jpg"
    ],
    badge: "Deva Mani",
    mukhi: "14 Mukhi",
    deity: "Lord Shiva & Lord Hanuman",
    rulingPlanet: "Saturn (Shani) & Mars (Mangal)",
    origin: "Nepali",
    highlight: "Original Nepali 14 Mukhi Rudraksha known as Deva Mani, blessed by Lord Shiva & Lord Hanuman. Awakens the Ajna Chakra with Govt Lab Certification.",
    tags: ["Deva Mani", "Awakens Ajna Chakra", "Supreme Intuition & Victory", "Govt Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "1",
    slug: "1-mukhi-rudraksha",
    name: "1 Mukhi Rudraksha (Nepali) — Lab Certified Ek Mukhi Supreme Bead",
    price: 3499,
    comparePrice: 4999,
    mrp: 4999,
    rating: 4.9,
    reviews: 86,
    reviewCount: 86,
    img: "/images/product-1mukhi.jpg",
    images: [
      "/images/product-1mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-mala.jpg",
      "/images/product-7mukhi.jpg"
    ],
    badge: "Popular",
    mukhi: "1 Mukhi",
    deity: "Lord Shiva (Paramshiva)",
    rulingPlanet: "Sun (Surya)",
    origin: "Nepali",
    highlight: "The supreme bead representing pure consciousness and Lord Shiva himself, accompanied by an authentic identification lab card.",
    tags: ["Supreme Consciousness", "Direct Realization", "Highest Path to Moksha", "Rare Collector Bead", "Lab Tested"],
    category: "Rudraksha",
    status: "Active",
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "2",
    slug: "2-mukhi-rudraksha",
    name: "2 Mukhi Rudraksha (Nepali) — Do Mukhi Ardhanarishvara Bead",
    price: 1199,
    comparePrice: 1799,
    mrp: 1799,
    rating: 4.8,
    reviews: 58,
    reviewCount: 58,
    img: "/images/product-5mukhi.jpg",
    images: [
      "/images/product-5mukhi.jpg",
      "/images/product-1mukhi.jpg",
      "/images/product-7mukhi.jpg"
    ],
    badge: "Relationship Harmony",
    mukhi: "2 Mukhi",
    deity: "Lord Ardhanarishvara (Shiva-Parvati)",
    rulingPlanet: "Moon (Chandra)",
    origin: "Nepali",
    highlight: "Symbolizes Lord Ardhanarishvara representing emotional unity, marital harmony, and inner peace. Calms Chandra Dosha.",
    tags: ["Marital Harmony", "Emotional Stability", "Chandra Dosha Shanti", "Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 35,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "3",
    slug: "3-mukhi-rudraksha",
    name: "3 Mukhi Rudraksha (Nepali) — Teen Mukhi Agni Swaroop Bead",
    price: 1099,
    comparePrice: 1699,
    mrp: 1699,
    rating: 4.8,
    reviews: 47,
    reviewCount: 47,
    img: "/images/product-7mukhi.jpg",
    images: [
      "/images/product-7mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-11mukhi.jpg"
    ],
    badge: "Vitality & Confidence",
    mukhi: "3 Mukhi",
    deity: "Lord Agni Dev & Mangal",
    rulingPlanet: "Mars (Mangal)",
    origin: "Nepali",
    highlight: "Blessed by Lord Agni to burn past negative karmas, dissolve inferiority complex, and instill vigorous confidence.",
    tags: ["Agni Swaroop", "Past Karma Cleansing", "Dynamic Energy", "Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 40,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "4",
    slug: "4-mukhi-rudraksha",
    name: "4 Mukhi Rudraksha (Nepali) — Chaar Mukhi Brahma & Saraswati Bead",
    price: 1149,
    comparePrice: 1749,
    mrp: 1749,
    rating: 4.9,
    reviews: 62,
    reviewCount: 62,
    img: "/images/product-5mukhi.jpg",
    images: [
      "/images/product-5mukhi.jpg",
      "/images/product-7mukhi.jpg",
      "/images/product-1mukhi.jpg"
    ],
    badge: "Wisdom & Memory",
    mukhi: "4 Mukhi",
    deity: "Lord Brahma & Goddess Saraswati",
    rulingPlanet: "Mercury (Budh)",
    origin: "Nepali",
    highlight: "Represents Lord Brahma and Maa Saraswati. Boosts intellect, sharp vocal communication, and academic excellence.",
    tags: ["Intellect & Memory", "Communication Power", "Budh Dosha Shanti", "Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "5",
    slug: "5-mukhi-rudraksha",
    name: "5 Mukhi Rudraksha (Nepali) — Consecrated & Lab Certified Paanch Mukhi",
    price: 999,
    comparePrice: 1499,
    mrp: 1499,
    rating: 4.9,
    reviews: 120,
    reviewCount: 120,
    img: "/images/product-5mukhi.jpg",
    images: [
      "/images/product-5mukhi.jpg",
      "/images/product-mala.jpg",
      "/images/product-7mukhi.jpg",
      "/images/product-1mukhi.jpg",
      "/images/product-11mukhi.jpg"
    ],
    badge: "Best Seller",
    mukhi: "5 Mukhi",
    deity: "Lord Kalagni Rudra",
    rulingPlanet: "Jupiter (Brihaspati / Guru)",
    origin: "Nepali",
    highlight: "Sacred soil (मिट्टी) & Holy Ganga Jal consecration from Mount Kailash region with certified Vedic energization.",
    tags: ["Shiva's Living Presence", "Dissolves Negative Energy", "Inner Clarity & Focus", "Govt Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 50,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "6",
    slug: "6-mukhi-rudraksha",
    name: "6 Mukhi Rudraksha (Nepali) — Chhah Mukhi Lord Kartikeya Bead",
    price: 1199,
    comparePrice: 1799,
    mrp: 1799,
    rating: 4.8,
    reviews: 51,
    reviewCount: 51,
    img: "/images/product-7mukhi.jpg",
    images: [
      "/images/product-7mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-11mukhi.jpg"
    ],
    badge: "Courage & Focus",
    mukhi: "6 Mukhi",
    deity: "Lord Kartikeya (Skanda)",
    rulingPlanet: "Venus (Shukra)",
    origin: "Nepali",
    highlight: "Governed by Lord Kartikeya, the commander of divine armies. Grants willpower, supreme emotional balance, and charm.",
    tags: ["Lord Kartikeya Blessing", "Willpower & Stamina", "Shukra Harmonization", "Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 35,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "7",
    slug: "7-mukhi-rudraksha",
    name: "7 Mukhi Rudraksha (Nepali) — Saat Mukhi Goddess Mahalakshmi Bead",
    price: 1299,
    comparePrice: 1899,
    mrp: 1899,
    rating: 4.8,
    reviews: 64,
    reviewCount: 64,
    img: "/images/product-7mukhi.jpg",
    images: [
      "/images/product-7mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-11mukhi.jpg",
      "/images/product-mala.jpg"
    ],
    badge: "Auspicious Wealth",
    mukhi: "7 Mukhi",
    deity: "Goddess Mahalakshmi",
    rulingPlanet: "Saturn (Shani Dev)",
    origin: "Nepali",
    highlight: "Blessed by Goddess Mahalakshmi to attract abundance, career growth, and financial stability while alleviating Saturn obstacles.",
    tags: ["Mahalakshmi Grace", "Abundance & Prosperity", "Removes Saturn Obstacles", "100% Natural", "Vedic Energized"],
    category: "Rudraksha",
    status: "Active",
    stock: 40,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "8",
    slug: "8-mukhi-rudraksha",
    name: "8 Mukhi Rudraksha (Nepali) — Aath Mukhi Lord Ganesha Bead",
    price: 1499,
    comparePrice: 2199,
    mrp: 2199,
    rating: 4.9,
    reviews: 38,
    reviewCount: 38,
    img: "/images/product-11mukhi.jpg",
    images: [
      "/images/product-11mukhi.jpg",
      "/images/product-7mukhi.jpg",
      "/images/product-5mukhi.jpg"
    ],
    badge: "Obstacle Destroyer",
    mukhi: "8 Mukhi",
    deity: "Lord Ganesha (Vighnaharta)",
    rulingPlanet: "Rahu",
    origin: "Nepali",
    highlight: "Removes all impediments in business, legal matters, and life journeys. Brings wisdom, auspicious beginnings, and Rahu protection.",
    tags: ["Vighnaharta Ganesha", "Removes Impediments", "Rahu Shanti", "Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "9",
    slug: "9-mukhi-rudraksha",
    name: "9 Mukhi Rudraksha (Nepali) — Nau Mukhi Maa Durga Navadurga Bead",
    price: 1599,
    comparePrice: 2399,
    mrp: 2399,
    rating: 4.9,
    reviews: 44,
    reviewCount: 44,
    img: "/images/product-11mukhi.jpg",
    images: [
      "/images/product-11mukhi.jpg",
      "/images/product-1mukhi.jpg",
      "/images/product-7mukhi.jpg"
    ],
    badge: "Divine Shakti",
    mukhi: "9 Mukhi",
    deity: "Maa Durga (Navadurga)",
    rulingPlanet: "Ketu",
    origin: "Nepali",
    highlight: "Infused with the 9 forms of Goddess Durga. Bestows fearlessness, spiritual endurance, protective shield, and Ketu mitigation.",
    tags: ["Navadurga Shakti", "Fearlessness & Protection", "Ketu Dosha Shanti", "Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "10",
    slug: "10-mukhi-rudraksha",
    name: "10 Mukhi Rudraksha (Nepali) — Das Mukhi Lord Vishnu Protection Bead",
    price: 1649,
    comparePrice: 2499,
    mrp: 2499,
    rating: 4.9,
    reviews: 36,
    reviewCount: 36,
    img: "/images/product-1mukhi.jpg",
    images: [
      "/images/product-1mukhi.jpg",
      "/images/product-11mukhi.jpg",
      "/images/product-5mukhi.jpg"
    ],
    badge: "10 Directions Protection",
    mukhi: "10 Mukhi",
    deity: "Lord Vishnu (Dashavatar)",
    rulingPlanet: "All 9 Planets (Navagraha Shield)",
    origin: "Nepali",
    highlight: "Shields the wearer from negative influences in all 10 directions. Pacifies Navagraha disturbances and legal entanglements.",
    tags: ["Vishnu Protection", "Shields 10 Directions", "Navagraha Harmonizer", "Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "11",
    slug: "11-mukhi-rudraksha",
    name: "11 Mukhi Rudraksha (Nepali) — Ekadash Rudra Lord Hanuman Bead",
    price: 1699,
    comparePrice: 2499,
    mrp: 2499,
    rating: 4.9,
    reviews: 42,
    reviewCount: 42,
    img: "/images/product-11mukhi.jpg",
    images: [
      "/images/product-11mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-7mukhi.jpg",
      "/images/product-mala.jpg"
    ],
    badge: "Hanuman Blessing",
    mukhi: "11 Mukhi",
    deity: "Lord Hanuman (Ekadasha Rudra)",
    rulingPlanet: "Mars & Navagraha",
    origin: "Nepali",
    highlight: "Symbolizes Lord Hanuman (Ekadasha Rudra) providing immense physical courage, mental fortitude, and protection from fears.",
    tags: ["Lord Hanuman Blessings", "Courage & Protection", "Mental Fortitude", "Vedic Energized", "Govt Lab Certified"],
    category: "Rudraksha",
    status: "Active",
    stock: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "12",
    slug: "12-mukhi-rudraksha",
    name: "12 Mukhi Rudraksha (Nepali) — Barah Mukhi Surya Tejas Authority Bead",
    price: 1899,
    comparePrice: 2799,
    mrp: 2799,
    rating: 4.9,
    reviews: 39,
    reviewCount: 39,
    img: "/images/product-1mukhi.jpg",
    images: [
      "/images/product-1mukhi.jpg",
      "/images/product-7mukhi.jpg",
      "/images/product-5mukhi.jpg"
    ],
    badge: "Solar Radiance",
    mukhi: "12 Mukhi",
    deity: "Lord Surya (12 Adityas)",
    rulingPlanet: "Sun (Surya Dev)",
    origin: "Nepali",
    highlight: "Conveys the radiant energy of the 12 Adityas. Bestows administrative leadership, radiant charisma, and career authority.",
    tags: ["12 Adityas Energy", "Charisma & Authority", "Surya Tejas", "Govt Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "13",
    slug: "13-mukhi-rudraksha",
    name: "13 Mukhi Rudraksha (Nepali) — Terah Mukhi Lord Kamadeva & Indra Bead",
    price: 1999,
    comparePrice: 2999,
    mrp: 2999,
    rating: 4.9,
    reviews: 35,
    reviewCount: 35,
    img: "/images/product-7mukhi.jpg",
    images: [
      "/images/product-7mukhi.jpg",
      "/images/product-11mukhi.jpg",
      "/images/product-5mukhi.jpg"
    ],
    badge: "Charm & Desires",
    mukhi: "13 Mukhi",
    deity: "Lord Kamadeva & Lord Indra",
    rulingPlanet: "Venus (Shukra)",
    origin: "Nepali",
    highlight: "Symbol of Lord Kamadeva and King Indra. Bestows hypnotic charisma, magnetic attraction, business wealth, and marital charm.",
    tags: ["Lord Kamadeva Grace", "Charisma & Attraction", "Venus Harmonization", "Govt Lab Certified", "100% Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "gauri-shankar",
    slug: "gauri-shankar-rudraksha",
    name: "Original Gauri Shankar Rudraksha (Nepali) — Shiva-Parvati Union Bead",
    price: 4999,
    comparePrice: 7999,
    mrp: 7999,
    rating: 5.0,
    reviews: 53,
    reviewCount: 53,
    img: "/images/product-1mukhi.jpg",
    images: [
      "/images/product-1mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-7mukhi.jpg"
    ],
    badge: "Sacred Union",
    mukhi: "Gauri Shankar",
    deity: "Lord Shiva & Goddess Parvati",
    rulingPlanet: "Moon & Venus",
    origin: "Nepali",
    highlight: "Naturally joined twin bead symbolizing the divine cosmic union of Shiva and Shakti. The ultimate bead for family bliss and marital unity.",
    tags: ["Shiva Shakti Union", "Marital Bliss & Harmony", "Twin Conjoined Bead", "Lab Tested", "Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "ganesh",
    slug: "ganesh-rudraksha",
    name: "Original Ganesh Rudraksha (Nepali) — Natural Trunk Shaped Sacred Bead",
    price: 2499,
    comparePrice: 3899,
    mrp: 3899,
    rating: 4.9,
    reviews: 41,
    reviewCount: 41,
    img: "/images/product-7mukhi.jpg",
    images: [
      "/images/product-7mukhi.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-11mukhi.jpg"
    ],
    badge: "Lord Ganesha Trunk",
    mukhi: "Ganesh",
    deity: "Lord Ganesha",
    rulingPlanet: "Rahu & Ketu Harmonizer",
    origin: "Nepali",
    highlight: "Features a natural trunk-like elevation on the surface representing Lord Ganesha. Attracts success in all new ventures and studies.",
    tags: ["Natural Trunk Bead", "New Venture Success", "Vighnaharta Blessings", "Govt Lab Tested", "Nepali Origin"],
    category: "Rudraksha",
    status: "Active",
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mala",
    slug: "rudraksha-mala-108-beads",
    name: "Sacred 108+1 Rudraksha Japa Mala — Silk Hand-Knotted Nepali Beads",
    price: 1899,
    comparePrice: 2999,
    mrp: 2999,
    rating: 4.9,
    reviews: 98,
    reviewCount: 98,
    img: "/images/product-mala.jpg",
    images: [
      "/images/product-mala.jpg",
      "/images/product-5mukhi.jpg",
      "/images/product-7mukhi.jpg",
      "/images/product-1mukhi.jpg"
    ],
    badge: "Spiritual Choice",
    mukhi: "5 Mukhi Mala",
    deity: "Lord Shiva",
    rulingPlanet: "Jupiter",
    origin: "Nepali",
    highlight: "Traditional 108+1 japa & dhyana mala hand-knotted with silk thread, ideal for mantra chanting and daily protection.",
    tags: ["108+1 Sacred Count", "Hand-knotted Silk", "Japa & Meditation", "Protective Aura", "Natural Nepal Beads"],
    category: "Mala",
    status: "Active",
    stock: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
